### PR TITLE
Update to lab 2.0

### PR DESCRIPTION
**Pull request by vidartf**
- package upgrades
- phosphor -> lumino
- services refactor
- use new icon system

### CODE REVIEW

**Comment by vidartf** [comment]
@telamonian : Does the icon changes here seem like the right way to do things? I found I still had to add `jp-Icon jp-Icon-16` some places to get the right styling. Is this expected?

@jasongrout I noticed that if I try to change the kernel of a notebook by the drop-down menu, by selecting the same kernel name as I currently have, I get disconnected. Is there something wrong with how I connect to the `kernelChanged` signal?

**Comment by echarles** [comment]
> I'd strongly recommend that you style icons via typestyle, by passing style args directly into the icon render method (ie either `.element` or, as in your case, `.react`). Medium term, `jp-Icon` and `jp-Icon-16` may not stick around (though certainly those won't change before 3.0).
> 
> Now that its API is locked down, I'm currently working on a number of improvements to `LabIcon`, including the styling system. Would you find it helpful if (one or both):
> 
> a) icons were rendered with a default size (probably `16px` x `16px`)
> 
> b) there was a custom `size` style arg that set both `height` and `width`
> 
> I have no strong opinions on the sizing stuff, but I know that @echarles does. I want to collect more feedback before moving forward on that

Last time I have looked at the icons, I have been pleased to discover the `kind` attributed with value `launcherCard | toolbarButton | mainAreaTab | ...` and finally revised my previous comments where I was advocating for sizing controls. I have no strong opinion on it, but today I like the idea that the user should not impose a size in pixels, but rather rely on the components to size based on a `kind`. This would allow to ensure the components are portable on mobile or any other display... Then maybe new custom `kind` creation by the user should be possible?

**Comment by vidartf** [comment]
Preferably, I would want some system that indicated the intended size for some standard components, yes. Then have some sort of manual control as fallback. This way, I don't have to double check what the current icon size of a toolbar is, themes can change their size, and there might be a preference for pixel-perfect sizes.

**Comment by consideRatio** [comment]
Hi! Nice to see there is already a PR to support JupyterLab 2.0.0! I just arrived to attempt a fix myself, and it was already happening =)

I just wanted to mention that JupyterLab 2.0.0 has been released now!

**Comment by consideRatio** [comment]
Wieee! I see you just released 2.0.0 of this extension allowing it to work with JupyterLab 2! Thanks for your work @vidartf!

**Pull request merged**
